FROM registry.pyn.ru:5000/python3.7-ubuntu18-production:2019.01.15

RUN mkdir -p /home/building
WORKDIR /home/building

COPY hhwebutils hhwebutils
COPY hhwebutils_tests hhwebutils_tests
COPY setup.py setup.py
COPY README.md README.md
COPY MANIFEST.in MANIFEST.in

RUN python3.7 setup.py test
