FROM registry.pyn.ru/python3.7-ubuntu18-production:2020.12.28

RUN mkdir -p /home/building
WORKDIR /home/building

COPY hhwebutils hhwebutils
COPY hhwebutils_tests hhwebutils_tests
COPY setup.py setup.py
COPY README.md README.md
COPY MANIFEST.in MANIFEST.in

RUN python3.7 setup.py test
